requirement_generation_task:
  description: >
    Create a detailed Product Requirements Document and Technical Requirements Document for {user_input}
    by asking human relevant questions (try to keep question asked to human less then 3 and group the question)regarding the project using Humand Interaction tool. 
  expected_output: >
    After the confermation of the human give the Product Requirements Document and Technical Requirements Document in text fromat or question that the human need to answer.
  agent: business_analyst

execution_plannig_task:
  description: >
    Understand the Product Requirements Document and Technical Requirements Document you got from the 
    context for {user_input}and create a Software Design Document and Development Workflow Plan that contains detailed information about project execution.
    Do not add anything new example feature, modules or tech that is not mentioned in Software Design Document.
  expected_output: >
    Software Design Document in text format and Development Workflow Plan
    Development Workflow Plan should be structured like this:
    Feature Overview: What the component does (e.g., "Track phone usage time").
    Tech Stack: Tools/APIs per layer (e.g., "Android UsageStatsManager API - Frontend, SQLite - Backend").
    Execution Process: Ordered steps with Frontend/Backend labels and effort estimates:
    Step 1: Query usage data via Android API
    Step 2: Store data locally in SQLite 
    Step 3: Sync data to backend via REST API
    Dependencies: Whats needed first (e.g., "Android permissions setup").
    Assumptions/Risks: Clarify limits (e.g., "No backend API for usage tracking; relies on Android API").
    for all modules and features mentioned in the Software Design Document.
  agent: developer
  context: ["requirement_generation_task"]

task_list_creation_task:
  description: >
    Use the Software Design Document and Development Workflow Plan from the context provided to you for {user_input} and create a task list using which developers can execute the project and deliver it on time.
    Do not add anything new example feature, modules or tech , screen ect.. that is not mentioned in Software Design Document.
  expected_output: >
    Task list in text format structured into bullet points.
  agent: project_manager
  context: ["execution_plannig_task"]
